###
# Defines variables for WP-Palvelu instance
###
name: wordpress
production:
  #This is the siteurl of production wordpress
  domain: wp-palvelu.fi
  ssh_port: 10008
development:
  #Domains to be mapped in local /etc/hosts
  domains:
    - wordpress.dev
    - subdomain.wordpress.dev