###
# Defines variables for WP-Palvelu instance
###
name: bus
production:
  #This is the siteurl of production wordpress
  domain: bus.fi
  ssh_port: 10008
development:
  #Domains to be mapped in local /etc/hosts
  domains:
    - bus.dev
    - testing.bus.dev